services:
  wallet-db:
    image: postgres:15
    container_name: wallet-postgres-prod
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Aquí aseguramos la persistencia de datos
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-api:
    build: .
    container_name: wallet-backend
    profiles:
      - prod
    ports:
      - "8082:8082"
    environment:
      DB_DRIVER: postgres
      DB_SOURCE: postgresql://wallet_user:wallet_password@wallet-db:5432/wallet_db?sslmode=disable
      SERVER_ADDRESS: "0.0.0.0:8082"
    depends_on:
      wallet-db:
        condition: service_healthy # Aprovecha el healthcheck de la base de datos
    restart: on-failure
    networks:
      - wallet-network
  prometheus:
    image: prom/prometheus:latest
    container_name: wallet-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  pgdata: