name: Billetera Digital CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Análisis Estático (Linter)
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Configurar Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Ejecutar golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: .
  security:
    name: Auditoría de Seguridad (Govulncheck)
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Configurar Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Ejecutar govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
          
  test:
    name: Ejecutar Pruebas
    needs: lint
    runs-on: ubuntu-latest # El servidor virtual que nos presta GitHub
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: wallet_user
          POSTGRES_PASSWORD: wallet_password
          POSTGRES_DB: wallet_db
        ports:
          - 5432:5432
        # Health check para asegurar que Postgres está listo antes de correr las pruebas
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clonar el código
        uses: actions/checkout@v4

      - name: Configurar Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true # Acelera las ejecuciones futuras guardando las dependencias

      - name: Descargar dependencias
        run: go mod download

      - name: Ejecutar pruebas  e integración
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: wallet_user
          DB_PASSWORD: wallet_password
          DB_NAME: wallet_db
          DB_SSLMODE: disable
        # El comando -v nos da los detalles y ./... busca tests en todas las carpetas
        run: go test -v ./...